# Site settings
title: Ashley Rae Edwards and Calvin Yeates Doval
email: cydoval@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  Celebrating the wedding of Ashley Rae Edwards and Calvin Yeates Doval
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ashandcal.com" # the base hostname & protocol for your site

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

#gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-autoprefixer
